version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: goboilerplate-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goboilerplate
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pkg/infra/database/sql:/docker-entrypoint-initdb.d
      #- /etc/api/[service]/pkg/infra/database/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
  app:
    container_name: goboilerplate-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./configs:/app/configs
#      - /etc/api/[service]/configs:/app/configs
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: