version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: goboilerplate-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Iinvite3
      POSTGRES_DB: goboilerplate
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: