version: '3.8'

services:
#  dbmysqlam:
#    image: "mysql"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_DATABASE: "goamartha"
#      MYSQL_USER: "admin"
#      MYSQL_PASSWORD: "admin"
#    ports:
#      - "3308:3306"
  db:
    image: postgres:latest
    container_name: sql-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goamartha
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "5437:5432"