version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: goboilerplate-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goboilerplate
      TZ: Asia/Jakarta
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pkg/infra/database/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
  api:
    container_name: goboilerplate-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Jakarta
    volumes:
      - /var/infra/api/logs:/app/logs
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: