server:
  port: 3000
database:
  #url: postgres://admin:admin@db:5432/goboilerplate
  url: postgres://admin:admin@localhost:5432/goboilerplate
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 30m
encryption:
  #bcrypt_cost: 10 ##Production Improve Security and reduce performance
  bcrypt_cost: 4
jwt:
  secret: goboilerplate
  app_name: goboilerplate
  audience: goboilerplate
  exp_access_token: 15 #minute
  exp_refresh_token: 24 #hour
mail:
  host: smtp.example.com
  port: 587
  username: your-email@example.com
  password: your-email-password